<?php
/**
 * Mapa de rutas netas - Fase 10.
 */
return [
    'routes' => [
        'index.php' => 'app/Controllers/Web/index.php',
        'producto.php' => 'app/Controllers/Web/producto.php',
        'carrito.php' => 'app/Controllers/Web/carrito.php',
        'checkout.php' => 'app/Controllers/Web/checkout.php',
        'mi_cuenta.php' => 'app/Controllers/Web/mi_cuenta.php',
        'wishlist.php' => 'app/Controllers/Web/wishlist.php',
        'notificaciones.php' => 'app/Controllers/Web/notificaciones.php',
        'tracking.php' => 'app/Controllers/Web/tracking.php',
        'planes.php' => 'app/Controllers/Web/planes.php',
        'garantia.php' => 'app/Controllers/Web/garantia.php',
        'soporte.php' => 'app/Controllers/Web/soporte.php',
        'factura_pdf.php' => 'app/Controllers/Web/factura_pdf.php',
        'ficha_tecnica.php' => 'app/Controllers/Web/ficha_tecnica.php',
        'ficha_tecnica_pdf.php' => 'app/Controllers/Web/ficha_tecnica_pdf.php',
        'admin.php' => 'app/Controllers/Admin/admin.php',
        'soporte_admin.php' => 'app/Controllers/Admin/soporte_admin.php',
        'correos_empresa.php' => 'app/Controllers/Admin/correos_empresa.php',
        'analitica.php' => 'app/Controllers/Admin/analitica.php',
        'crear_admin.php' => 'app/Controllers/Admin/crear_admin.php',
        'proveedor.php' => 'app/Controllers/Proveedor/proveedor.php',
        'auth.php' => 'app/Controllers/Auth/auth.php',
        'google_auth.php' => 'app/Controllers/Auth/google_auth.php',
        'logout.php' => 'app/Controllers/Auth/logout.php',
        'api_producto.php' => 'app/Controllers/Api/api_producto.php',
        'api_filtros.php' => 'app/Controllers/Api/api_filtros.php',
        'api_filtrar_productos.php' => 'app/Controllers/Api/api_filtrar_productos.php',
        'api_guardar_producto.php' => 'app/Controllers/Api/api_guardar_producto.php',
        'api_wishlist.php' => 'app/Controllers/Api/api_wishlist.php',
        'buscar_sugerencias.php' => 'app/Controllers/Api/buscar_sugerencias.php',
        'add_to_cart.php' => 'app/Controllers/Api/add_to_cart.php',
        'cancelar_membresia.php' => 'app/Controllers/Actions/cancelar_membresia.php',
        'procesar_devolucion.php' => 'app/Controllers/Actions/procesar_devolucion.php',
        'recibir_devolucion.php' => 'app/Controllers/Actions/recibir_devolucion.php',
        'responder_devolucion.php' => 'app/Controllers/Actions/responder_devolucion.php',
        'banner_redirect.php' => 'app/Controllers/Actions/banner_redirect.php',
        'generar_etiqueta.php' => 'app/Controllers/Actions/generar_etiqueta.php',
        'imprimir_guia.php' => 'app/Controllers/Actions/imprimir_guia.php',
        'simulador_sucursales.php' => 'app/Controllers/Actions/simulador_sucursales.php',
        'crear_usuario_empresa.php' => 'app/Controllers/Tools/crear_usuario_empresa.php',
        'probar_correo_facturacion.php' => 'app/Controllers/Tools/probar_correo_facturacion.php',
        'verificar_phpmailer.php' => 'app/Controllers/Tools/verificar_phpmailer.php',
    ],
    'aliases' => [
        '' => 'index.php',
        '/' => 'index.php',
        'home' => 'index.php',
        'producto' => 'producto.php',
        'carrito' => 'carrito.php',
        'checkout' => 'checkout.php',
        'mi-cuenta' => 'mi_cuenta.php',
        'admin' => 'admin.php',
        'proveedor' => 'proveedor.php',
        'login' => 'auth.php',
        'auth' => 'auth.php',
        'wishlist' => 'wishlist.php',
        'notificaciones' => 'notificaciones.php',
        'tracking' => 'tracking.php',
        'planes' => 'planes.php',
        'soporte' => 'soporte.php',
    ],
];
?>
